Repository EbrahimMohamed2611/pet-store, pull requests merged in 2021-06, with the labels that each got.

#2 Added admin model & admin service.
  src/app/model/Admin.model.ts
  src/app/service/admin/admin.service.spec.ts
  src/app/service/admin/admin.service.ts
Labels: enhancement

#1 Feature seller service
  src/app/model/Seller.model.ts
  src/app/service/seller/seller.service.spec.ts
  src/app/service/seller/seller.service.ts
Labels: enhancement

#8 Added not found page.
  src/app/component/not-found/not-found.component.html
Labels: enhancement

#9 Feature: shop & product info pages
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/component/header/header.component.html
  src/app/component/product-info/product-info.component.css
  src/app/component/product-info/product-info.component.html
  src/app/component/product-info/product-info.component.spec.ts
  src/app/component/product-info/product-info.component.ts
  src/app/component/product/product.component.html
  src/app/component/product/product.component.ts
  src/app/component/shop/shop.component.css
  src/app/component/shop/shop.component.html
  src/app/component/shop/shop.component.spec.ts
  src/app/component/shop/shop.component.ts
  src/app/model/Brand.model.ts
  src/app/model/Image.model.ts
  src/app/model/Product.model.ts
  src/app/model/Products.model.ts
  src/app/model/Rate.model.ts
  src/app/service/brand/brand.service.spec.ts
  src/app/service/brand/brand.service.ts
  src/app/service/category/category.service.ts
  src/app/service/product/product.service.ts
  src/environments/environment.ts
  src/styles.css
Labels: enhancement

#10 Changing rate model to include userName instead of rateId.
  src/app/model/Rate.model.ts
Labels: bug

#17 Fixed product image slider in product info page & display sale badge …
  src/app/component/product-info/product-info.component.css
  src/app/component/product-info/product-info.component.html
  src/app/component/product-info/product-info.component.ts
  src/app/component/product/product.component.html
  src/environments/environment.ts
Labels: bug

#18 Enabling brand service in product shop.
  src/app/component/shop/shop.component.ts
Labels: bug

#19 Hotfix sale badge
  src/app/component/product-info/product-info.component.html
  src/app/component/product-info/product-info.component.ts
Labels: bug

#22 Fixed product undefined in the console.
  src/app/component/product-info/product-info.component.html
  src/app/component/product-info/product-info.component.ts
Labels: bug

#23 Hotfix home page
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/component/header/header.component.html
  src/app/component/home/home.component.html
  src/app/component/home/home.component.ts
  src/app/resolvers/home-products-resolver.service.spec.ts
  src/app/resolvers/home-products-resolver.service.ts
  src/app/resolvers/top-categories-resolver.service.spec.ts
  src/app/resolvers/top-categories-resolver.service.ts
  src/app/resolvers/top-offers-resolver.service.spec.ts
  src/app/resolvers/top-offers-resolver.service.ts
  src/app/resolvers/top-rated-resolver.service.spec.ts
  src/app/resolvers/top-rated-resolver.service.ts
  src/environments/environment.ts
Labels: bug

#25 Fixed price slider.
  src/app/app.module.ts
  src/app/component/product-info/product-info.component.ts
  src/app/component/services-shop/services-shop.component.html
  src/app/component/services-shop/services-shop.component.ts
  src/app/component/shop/shop.component.css
  src/app/component/shop/shop.component.html
  src/app/component/shop/shop.component.ts
  src/styles.css
Labels: bug

#26 Fixing products in home page & shopping cart and my account buttons.
  src/app/component/header/header.component.html
  src/app/component/header/header.component.ts
  src/app/component/home/home.component.html
  src/app/component/home/home.component.ts
Labels: bug, enhancement

#27 Feature search
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/component/header/header.component.html
  src/app/component/header/header.component.ts
  src/app/component/not-found/not-found.component.html
  src/app/component/not-found/not-found.component.ts
  src/app/component/search-result/search-result.component.css
  src/app/component/search-result/search-result.component.html
  src/app/component/search-result/search-result.component.spec.ts
  src/app/component/search-result/search-result.component.ts
  src/app/service/search/search.service.spec.ts
  src/app/service/search/search.service.ts
Labels: enhancement

#28 fix production api url
  src/environments/environment.prod.ts
Labels: bug
